### ISSUE TITLE
Type mapping not working

### ISSUE THREAD

**Issue by SamuelNitsche** [swisnl/json-api-client-laravel#3]
## Detailed description

I tried to map a resource to a class using [this example](https://github.com/swisnl/json-api-client-laravel#mapping-types). However, this does not work. It seems like the package internals don't resolve the `TypeMapper` class correctly so there are actually no mappings defined when calling the `hasMapping` method on the `TypeMapper`.

## Your environment

* Version used (e.g. PHP 5.6, HHVM 3): PHP 8.1
* Operating system and version (e.g. Ubuntu 16.04, Windows 7): macOS 12.3.1

**Comment by JaZo** [comment]
It might be a silly question, but did you register your `TypeMapperServiceProvider` in your application? If so, can you post a full code example?

**Comment by JaZo** [comment]
Closing this stale issue, feel free to reopen when the issue is still present!
